#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
  _crash_bash="${_lib}/libcrash-bash/crash-bash"
  _libevm="${_lib}/libevm/libevm"
  _sourced \
    "${_crash_bash}" 2>/dev/null || \
    source \
    "${_crash_bash}"
  _sourced \
    "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  call_date=""
  wallet_name=""
  wallet_path=""
  wallet_password=""
  wallet_seed=""
  wallet_address=""
  gnupg_home=""
  input_type=""
  output_type=""
  key_passphrase=""
  key_type=""
  key_comment=""
  target_command=""
  target_key=""
  target_value=""
  with_colons=""
  command_args=()
  cache_dir=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'libevm-requirements'
  libevm-requirements
  _check_cmd \
    'evm-wallet'
  }

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/evm-gnupg"
  echo \
    "${_dir}"
  }

# Generate an OpenPGP key for the input address
_key_new() {
  local \
    _gnupg_home="${1}" \
    _email="${2}" \
    _name="${3}" \
    _passphrase="${4}" \
    _comment="${5}" \
    _gpg_conf_array=() \
      _gpg_generate_array=() \
        _gpg_opts=()
  _gpg_opts+=(
    --homedir
    "${_gnupg_home}"
    --gen-key
  )
  _gpg_conf_array+=(
    "quiet"
    "batch"
    "no-tty"
    "no-permission-warning"
    "export-options no-export-attributes,export-clean"
    "list-options no-show-keyring"
    "armor"
    "no-emit-version"
  )
  _gpg_generate_array+=(
    "%echo Generating key pair for '${_name}'..."
    "Key-Type: eddsa"
    "Key-Curve: ed25519"
    # "Key-Length: 4096"
    "Key-Usage: sign"
    "SubKey-Type: ecdh"
    "SubKey-Curve: cv25519"
    "SubKey-Usage: encrypt"
    "Name-Real: ${_name}"
  )
  if [[ "${_comment}" != "" ]]; then
    _gpg_generate_array+=(
      "Name-Comment: ${_comment}"
    )
  fi
  _gpg_generate_array+=(
    "Name-Email: ${_email}"
  )
  if [[ "${_passphrase}" != "" ]]; then
    _gpg_generate_array+=(
      "Passphrase: ${_passphrase}"
    )
  fi
  _gpg_generate_array+=(
    "Expire-Date: 0"
  )
  if [[ "${_passphrase}" == "" ]]; then
    _gpg_generate_array+=(
      "%no-protection"
    )
  fi
  _gpg_generate_array+=(
    "%commit"
    "%echo Done"
  )
  mkdir \
    -p \
    "${_gnupg_home}"
  chmod \
    700 \
    "${_gnupg_home}"
  cat << \
    __EOF__ > \
      "${_gnupg_home}"/gpg.conf
$(printf \
    '%s\n' \
    "${_gpg_conf_array[@]}")
__EOF__
gpg \
  "${_gpg_opts[@]}" <<EOF
$(printf \
    '%s\n' \
    "${_gpg_generate_array[@]}")
EOF
}

_keys_secret_list() {
  local \
    _gnupg_home="${1}" \
    _output_type="${2}" \
    _query="${3}" \
    _gpg_opts=() \
    _gpg_key_info_opts=() \
    _list \
    _out \
    _key
  if [[ "${quiet}" == "n" ]]; then
    _gpg_key_info_opts+=(
      -v
    )
  fi
  _key="${_cache_dir}/key.asc"
  _gpg_opts+=(
    --homedir
    "${_gnupg_home}"
  )
  if [[ "${_output_type}" == "fingerprint" ]]; then
    _with_colons="y"
  fi
  if [[ "${_with_colons}" == "y" ]]; then
    _gpg_opts+=(
      --with-colons
    )
  fi
  if [[ "${_output_type}" == "" ]]; then
    if [[ "${_key_type}" == "public" ]]; then
      _list="--list-keys"
    elif [[ "${_key_type}" == "private" ]]; then
      _list="--list-secret-keys"
    fi
    _gpg_opts+=(
      "${_list}"
    )
    if [[ "${_query}" != "" ]]; then
      _gpg_opts+=(
        "${_query}"
      )
    fi
    _msg=(
      "Running gpg with options"
      "'${_gpg_opts[*]}'."
    )
    _msg_info \
    "${_msg[*]}"
    GNUPGHOME="${_gnupg_home}" \
    gpg \
      "${_gpg_opts[@]}"
  else
    if [[ "${_key_type}" == "public" ]]; then
      _export="--export"
    elif [[ "${_key_type}" == "private" ]]; then
      _export="--export-secret-keys"
    fi
    _gpg_opts+=(
      "${_export}"
      --armor
    )
    if [[ "${_query}" != "" ]]; then
      _gpg_opts+=(
        "${_query}"
      )
    fi
    _msg=(
      "Running gpg with options"
      "'${_gpg_opts[*]}'."
    )
    _msg_info \
      "${_msg[*]}"
    GNUPGHOME="${_gnupg_home}" \
    gpg \
      "${_gpg_opts[@]}" > \
      "${_key}"
    _gpg_key_info_opts+=(
      -t
        "${_key_type}"
      -o
        "${_output_type}"
    )
    _msg=(
      "Running gpg-key-info with options"
      "'${_gpg_key_info_opts[*]}'."
    )
    _msg_info \
      "${_msg[*]}"
    gpg-key-info \
      "${_gpg_key_info_opts[@]}" \
      "${_key}"
  fi
}

_address_detect() {
  local \
    _address="${1}"
  if (( 42 == "${_address}" && \
        "${_address}" == "0x"* )); then
    _msg=(
      "Detected address type."
    )
    _msg_info \
      "${_msg[*]}"
    _address_sanity_check \
      "${_address}"
  fi
}

_keys_import() {
  local \
    _gnupg_home="${1}" \
    _source_import="${2}" \
    _export_opts=() \
    _import_opts=() \
    _export_secret \
    _address
  if [[ -d "${_source_import}" ]]; then
    _export_secret="${_cache_dir}/secret.asc"
    _export_opts+=(
      --homedir
        "${_source_import}"
      --export-secret-key
      --armor
    )
    _import_opts+=(
      --homedir
        "${_gnupg_home}"
      --import
    )
    gpg \
      "${_export_opts[@]}" > \
      "${_export_secret}"
    gpg \
      "${_import_opts[@]}" \
      "${_export_secret}"
    rm \
      -rf \
      "${_export_secret}"
  else
    _address_detect \
      "${_source_import}"
    if [[ "${_source_import}" != "" ]]; then
      _msg=(
        "Retrieving key from EVM"
        "OpenPGP Key Server."
      )
      _msg_info \
        "${_msg[*]}"
      _keys_receive \
        "${_source_import}"
    fi
  fi
}

# _keys_names_get() {
#   local \
#     _gnupg_home="${1}" \
#     _filter="${2}" \
#     _gpg_out \
#     _gpg_opts=() \
#     _address
#   _gpg_opts+=(
#     --homedir
#       "${_gnupg_home}"
#     --with-colons
#     --list-keys
#     "@${_address}"
#   )
#   # awk \
#   #  -F \
#   #    ":" \
#   #  '{print $1}'
# }

_keys_enumerate() {
  local \
    _gnupg_home="${1}" \
    _wallet_address="${2}" \
    _gpg_out \
    _gpg_opts=()
  _gpg_opts+=(
    --homedir
      "${_gnupg_home}"
    --with-colons
    --list-keys
    "@${_address}"
  )
  _keys_amount="$(
    gpg \
      "${_gpg_opts[@]}" | \
      grep \
        "\buid:" | \
        wc \
          -l)"
}

_gpg_export() {
  local \
    _gnupg_home="${1}" \
    _out_file="${2}" \
    _key_type="${3}" \
    _query="${4}" \
    _gpg_opts=() \
    _out_dir \
    _export_opt
  if [[ "${_key_type}" == "" ]]; then
    _msg=(
      "Export type not set,"
      "selecting 'public key'."
    )
    _msg_info \
      "${_msg[*]}"
    _key_type="public"
  fi
  _gpg_opts+=(
    --homedir
      "${_gnupg_home}"
  )
  if [[ "${_key_type}" == "public" ]]; then
    _export_opt="--export"
  elif [[ "${_key_type}" == "private" ]]; then
    _export_opt="--export-secret-keys"
  else
    _msg=(
      "Unknown key export type"
      "'${_key_type}'."
      "Valid values are 'public'"
      "and 'private'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _gpg_opts+=(
    "${_export_opt}"
    --armor
    "${_query}"
  )
  if [[ "${_out_file}" == "" ]]; then
    gpg \
      "${_gpg_opts[@]}"
  elif [[ "${_out_file}" != "" ]]; then
    _out_dir="$(
      dirname \
        "${_out_file}")"
    if [[ ! -d "${_out_dir}" ]]; then
      _msg=(
        "Directory '${_out_dir}'"
        "does not exist."
      )
      _msg_error \
        "${_msg[*]}" \
        1
    fi
    gpg \
      "${_gpg_opts[@]}" > \
      "${_out_file}"
  fi
}

_keys_export() {
  local \
    _gnupg_home="${1}" \
    _wallet_name="${2}" \
    _out_file="${3}" \
    _key_type="${4}" \
    _gpg_opts=() \
    _export_opts=() \
    _import_opts=() \
    _export_secret \
    _keys_amount \
    _address
  _address="$(
    evm-wallet \
      get \
        "${_wallet_name}" \
        "address")"
  _keys_enumerate \
    "${_gnupg_home}" \
    "${_address}"
  if (( 0 == "${_keys_amount}" )); then
    _msg=(
      "No GPG keys found for wallet"
      "'${_wallet_name}' with address"
      "${_address}"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  elif (( 1 < "${_keys_amount}" )); then
    _msg=(
      "Found more than a key"
      "for account '${_wallet_name}'"
      "with address '${_address}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _gpg_export \
    "${_gnupg_home}" \
    "${_out_file}" \
    "${_key_type}" \
    "@${_address}"
}

_keys_dir() {
  local \
    _data_dir=
  _data_dir="${HOME}/.local/share/${app_name}"
  _keys_dir="${_data_dir}/${}"
}

_keys_receive() {
  local \
    _address="${1}" \
    _contact_name \
    _evm_openpgp_key_receive_opts=() \
    _receive_input_type \
    _keys_dir \
    _key \
    _address
  # _keys_dir=""
  if [[ "${quiet}" == "n" ]]; then
    _evm_openpgp_key_receive_opts+=(
      -v
    )
  fi
  if [[ "${_input_type}" == "address" ]]; then
    _receive_input_type="number"
  elif [[ "${_input_type}" == "fingerprint" ]]; then
    _receive_input_type="fingerprint"
    _address="$(
      evm-wallet \
        get \
        "${_wallet_name}" \
        "address")"
  elif [[ "${_input_type}" == "contact" ]]; then
    _receive_input_type="number"
    _contact_name="${_target_key}"
    _key="$(
      evm-wallet \
        get \
        "${_contact_name}" \
        "address")"
  fi
  _keys_dir="${HOME}/.local/share/${app_name}/"
  _evm_openpgp_key_receive_opts+=(
    -H
      "${_gnupg_home}"
    -t
      "${_receive_input_type}"
    -f
      "n"
    -P
      "${_key}"
    # -o
    #   "${_keys_dir}"
  )
  evm-openpgp-key-receive \
    "${_evm_openpgp_key_receive_opts[@]}" \
    "${_key}"
}

_output_type_check() {
  local \
    _output_types=()
  _output_types+=(
    "email"
    "fingerprint"
    "name"
  )
  if [[ " ${_output_types[*]} " != *" ${_output_type} "* ]]; then
    _msg=(
      "Unknown output type"
      "'${_output_type}'."
      "Valid types are"
      "'email', 'fingeprint'"
      "and 'name'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_evm_gpg() {
  local \
    _wallet_name="${1}" \
    _wallet_path="${2}" \
    _wallet_password="${3}" \
    _wallet_seed="${4}" \
    _gnupg_home="${5}" \
    _key_passphrase="${6}" \
    _key_comment="${7}" \
    _with_colons="${8}" \
    _input_type="${9}" \
    _output_type="${10}" \
    _key_type="${11}" \
    _cache_dir="${12}" \
    _target_command="${13}" \
    _target_key="${14}" \
    _target_value="${15}" \
    _command_args=() \
    _args=() \
    _address \
    _name \
    _email \
    _full_name \
    _source_import \
    _out_file \
    _output_type
  shift \
    15
  _command_args+=(
    "$@"
  )
  _output_type_check
  if [[ "${_target_command}" == "new" ]]; then
    _address="$(
      evm-wallet \
       get \
         "${_wallet_name}" \
         "address")"
    _name="${_target_key}"
    _email="${_name}@${_address}"
    _full_name="${_target_value}"
    _key_new \
      "${_gnupg_home}" \
      "${_email}" \
      "${_full_name}" \
      "${_key_passphrase}" \
      "${_key_comment}"
  elif [[ "${_target_command}" == "export" ]]; then
    _out_file="${_target_key}"
    _keys_export \
      "${_gnupg_home}" \
      "${_wallet_name}" \
      "${_out_file}" \
      "${_key_type}"
  elif [[ "${_target_command}" == "import" ]]; then
    _source_import="${_target_key}"
    _keys_import \
      "${_source_import}"
  elif [[ "${_target_command}" == "list" ]]; then
    _address=""
    if [[ "${_wallet_name}" != "" ]]; then
      _address="$(
        evm-wallet \
         get \
           "${_wallet_name}" \
           "address")"
    fi
    _query="${_target_key}"
    # _output_type="${_target_value}"
    if [[ "${_query}" == "" && \
          "${_address}" != "" ]]; then
      _query="@${_address}"
    fi
    _keys_secret_list \
      "${_gnupg_home}" \
      "${_output_type}" \
      "${_query}"
  elif [[ "${_target_command}" == "receive" ]]; then
    _address="${_target_key}"
    _keys_receive \
      "${_address}"
  else
    _msg=(
      "Unknown command '${_target_command}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_gnupg_home_auto_detect() {
  local \
    _gnupg_home \
    _gnupg_home_default
  _gnupg_home=""
  _gnupg_home_default="$(
    _get_conf_dir_path)"
  if [[ ! -v "override_gnupg_home" ]]; then
    if [[ ! -d "${_gnupg_home}" ]]; then
      mkdir \
        -p \
        "${_gnupg_home_default}"
      chmod \
        700 \
        "${_gnupg_home_default}"
    fi
    _gnupg_home="${_gnupg_home_default}"
  fi
  _set_override \
    "gnupg" \
    "home" \
    "${_gnupg_home}"
}

_target_key_check() {
  local \
    _msg=() \
    _flag
  _flag="false"
  if [[ "${target_command}" == "new" ]]; then
    if [[ "${target_key}" == "" ]]; then
      _flag="true"
      _msg=(
        "You are creating a key without"
        "setting an username."
      )
    fi
  elif [[ "${target_command}" == "receive" ]]; then
    if [[ "${target_key}" == "" ]]; then
      _flag="true"
      _msg=(
        "You need to specify either"
        "an address or a contact name"
        "of which to retrieve the"
        "OpenPGP keys."
      )
    fi
  fi
  if [[ "${_flag}" == "true" ]]; then
    _msg_error \
      "${_msg[*]}" \
      0
    _usage \
      1
  fi
}

_target_value_check() {
  local \
    _msg=()
  if [[ "${target_value}" == "" ]]; then
    _msg=(
      "You are creating a key without"
      "setting a name."
    )
    _msg_error \
      "${_msg[*]}" \
      0
    _usage \
      1
  fi
}

_key_passphrase_check() {
  local \
    _msg=()
  if [[ "${key_passphrase}" == "" ]]; then
    _msg=(
      "You are creating a key without"
      "a passphrase."
    )
    _msg_warning \
      "${_msg[*]}"
  fi
}

_contact_sanity_check() {
  local \
    _target_contact="${1}" \
    _evm_wallet_opts=() \
    _contacts_names=() \
    _contacts_string \
    _contact
  _contact_assert="false"
  _evm_wallet_opts+=(
    -o
      "name"
  )
  _contacts_string="$(
    evm-wallet \
      "${_evm_wallet_opts[@]}" \
      list)"
  IFS='\n' \
  read \
    -ra \
    _contacts_names <<< "${_contacts_string}"
  for _contact in "${_contacts_names[@]}"; do
    if [[ "${_contact}" == "${_target_contact}" ]]; then
      _contact_assert="true"
      break
    fi
  done
}

_input_type_auto_detect() {
  local \
    _contact_assert \
    _address_assert \
    _input_type
  _input_type=""
  if [[ "${target_command}" == "receive" ]]; then
    _address_assert="$(
      _address_sanity_check \
        "${target_key}" \
        "0")"
    if [[ "${_address_assert}" == "" ]]; then
      _input_type="address"
    elif [[ "${_address_assert}" != "" ]]; then
      _contact_sanity_check \
        "${target_value}"
      if [[ "${_contact_assert}" == "true" ]]; then
        _input_type="contact"
      else
        _msg=(
          "Input is not a wallet address,"
          "assuming it is a key fingerprint."
        )
        _msg_info \
          "${_msg[*]}"
        _input_type="fingerprint"
      fi
    fi
  fi
  _set_override \
    "input" \
    "type" \
    "${_input_type}"
}

_cache_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/${app_name}"
  if [[ ! -v "override_cache_dir" ]]; then
    if [[ ! -d "${_dir}" ]]; then
      mkdir \
        -p \
        "${_dir}"
      chmod \
        700 \
        "${_dir}"
    fi
  fi
  _set_override \
    "cache" \
    "dir" \
    "${_dir}"
}

_set_overrides() {
  local \
    _msg=() \
    _wallet_name
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "call" \
    "date" \
    "$(_get_date_human)"
  _cache_dir_auto_detect
  _set_override \
    "target" \
    "command" \
    "list"
  _wallet_name=""
  if [[ "${target_command}" != "list" ]]; then
    _wallet_name="default"
  fi
  _set_override \
    "wallet" \
    "name" \
    "${_wallet_name}"
  _wallet_overrides_set \
    "evm-wallet" \
    "${wallet_name}" \
    "n" # "${call_auth}"
  if [[ "${wallet_name}" != "" ]]; then
    _set_override \
      "wallet" \
      "address" \
      "$(evm-wallet \
           get \
             "${wallet_name}" \
             "address")"
  fi
  _gnupg_home_auto_detect
  _set_override \
    "target" \
    "key" \
    ""
  _set_override \
    "target" \
    "value" \
    ""
  _set_override \
    "key" \
    "passphrase" \
    ""
  _set_override \
    "key" \
    "comment" \
    ""
  _set_override \
    "key" \
    "type" \
    "public"
  _target_key_check
  if [[ "${target_command}" == "new" ]]; then
    _target_value_check
    _key_passphrase_check
  fi
  _set_override \
    "with" \
    "colons" \
    "n"
  _set_override \
    "output" \
    "type" \
    ""
  _input_type_auto_detect
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

GNUPG wrapper for use by the EVM Toolchain

Usage:
  ${app_name}
    [options]
    <command>
    <key>
    <value>

  commands:
    new
      <username>
      <full-name>
    list
      (<filter>)
    import
      <import-source>
    export
      <out-file>
    receive
      <address>      or <fingerprint>
      (<key-number>)

  list args:
    filter

  import sources:
    directory               GNUPG home directory
                            from which to import the key.
    fingerprint             A key fingerprint.
    file                    A key file.

  key type:
    public
    private 

  options:
     -H <gnupg-home>        GNUPG home directory
                            Default: ${gnupg_home}
     -t <key-type>          It can be empty, 'fingerprint'
                            'name' or 'email'.
                            Default: ${key_type}
     -Q                     If enabled, passes the '--with-colons'
                            serializing option to GPG.
                            Default: ${with_colons}

  key creation options:
     -P <passphrase>        Key passphrase (for 'new' command).
                            Default: ${key_passphrase}
     -C <comment>           Key comment (for 'new' command).
                            Default: ${key_comment}

  list options:
     -o <output-type>       It can be empty, 'fingerprint',
                            'name' or 'email'.
                            Default: ${output_type}

  receive options:
     -i <input-type>        It can be 'auto', 'address',
                            'contact'.
                            Default: ${input_type}

  credentials options:
     -N <wallet-name>       Wallet name.
                            Default: ${wallet_name}
     -w <wallet-path>       Wallet path.
                            Default: ${wallet_path}
     -p <wallet-password>   Wallet password.
                            Default: ${wallet_password}
     -s <wallet-seed>       Wallet seed path.
                            Default: ${wallet_seed}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flag \
    _flags=(
      "${1}"
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _passphrase_show
  if [[ "${key_passphrase}" != "" ]]; then
    _passphrase_show="****"
  fi
  _msg_info "${app_name} configuration"
  _msg_info "                Call date:   ${call_date}"
  _msg_info "           Target command:   ${target_command}"
  _msg_info "               Target key:   ${target_key}"
  _msg_info "             Target value:   ${target_value}"
  _msg_info "               Input type:   ${input_type}"
  _msg_info "              Output type:   ${output_type}"
  _msg_info "              With colons:   ${with_colons}"
  _msg_info "          GNUPG directory:   ${gnupg_home}"
  _msg_info "        New key options:"
  _msg_info "           Key passphrase:   ${_passphrase_show:-}"
  _msg_info "              Key comment:   ${key_comment}"
  _msg_info "    Credentials options:"
  _msg_info "              Wallet name:   ${wallet_name}"
  _msg_info "           Wallet address:   ${wallet_address}"
  _msg_info "              Wallet path:   ${wallet_path}"
  _msg_info "          Wallet password:   ${wallet_password}"
  _msg_info "              Wallet seed:   ${wallet_seed}"
  _msg_info "    Application options:"
  _msg_info "          Cache directory:   ${cache_dir}"
}

_globals
_global_variables
_libevm_global_variables
_requirements
getopts_opts="$(
  printf \
    "%s" \
    "H:P:C:Qo:" \
    "C:" \
    "$(_libevm_app_getopts_params_get)" \
    "n:" \
    "$(_wallet_getopts_params_get)" \
    "W:cvh")"
# shellcheck disable=SC2034
while \
  getopts \
    "${getopts_opts}" \
    arg; do
  _wallet_getopts_case
  _libevm_app_getopts_case
  case \
    "${arg}" in
    N)
      override_wallet_name="${OPTARG}" ;;
    w)
      override_wallet_path="${OPTARG}" ;;
    p)
      override_wallet_password="${OPTARG}" ;;
    s)
      override_wallet_seed="${OPTARG}" ;;
    H)
      override_gnupg_home="${OPTARG}" ;;
    P)
      override_key_passphrase="${OPTARG}" ;;
    C)
      override_key_comment="${OPTARG}" ;;
    Q)
      override_with_colons="y" ;;
    t)
      override_key_type="${OPTARG}" ;;
    o)
      override_output_type="${OPTARG}" ;;
    W)
      override_cache_dir="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h)
      _set_overrides && \
         _usage \
           0 ;;
    *)
      if [[ " ${getopts_opts} " != *"${arg}"* ]]; then
        _msg=(
          "Invalid argument '${arg}'."
        )
        _msg_error \
          "${_msg[*]}" \
          0
        _usage \
          1
      fi ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg=(
    "No command given."
  )
  _msg_error \
    "${_msg[*]}" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < "${#}" )); then
  target_command="${1}"
fi
if (( 1 < "${#}" )); then
  target_key="${2}"
fi
if (( 2 < "${#}" )); then
  target_value="${3}"
fi
shift \
  3 || \
true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${gnupg_home}"
  "${key_passphrase}"
  "${key_comment}"
  "${with_colons}"
  "${input_type}"
  "${output_type}"
  "${key_type}"
  "${cache_dir}"
  "${target_command}"
  "${target_key}"
  "${target_value}"
  "${command_args[@]}"
)
_evm_gpg \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
